"""Generated by `python -m backend.scripts.import_bulk_infra` -- NOT auto-merged into
infrastructure.py. Review each entry (accuracy, region_keys, dedup against the
hand-curated lists) before folding into INFRA_SITES / MILITARY_BASES.
Generated at 2026-08-04 10:50:23 UTC.
"""

IMPORTED_INFRA_SITES: list[dict] = [
]


IMPORTED_MILITARY_BASES: list[dict] = [
]
