"""backend/sources/sat_passes.py -- Task 25's overpass prediction.

Three cases the brief calls out by name: a known satellite over a known
point checked against a precomputed answer, the no-passes case, and the
work cap. A fourth block exercises the /api/satellites/passes route itself
(lat/lon validation, the groups filter, the response shape), the same
"pure function first, then the thin route wrapper" split
test_satellites.py already uses for satellite_elements.

No live network anywhere here, per this repo's test discipline: the same
ISS-shaped OMM fixture test_satellites.py uses (fixed epoch, so a re-run
next year can't silently start seeing a different answer), decorated
through satellites._decorate_element the same way the real collector does
-- so this test exercises the real inclination_deg/apogee_km fields the
reachability filter reads, not a hand-typed stand-in for them.

The "known point/precomputed answer" case was generated by running
skyfield directly against this exact fixture (Tokyo, 35.7N 139.7E, an hour
after the fixture's own epoch) and recording what it actually returned --
see this file's own comment above the assertions for the numbers. Rise/
culminate/set are compared with a few seconds' tolerance rather than exact
string equality: skyfield's internal root-finder takes a slightly different
numerical path depending on the search window's length (`hours`), so the
same pass's set time can differ by a whole displayed second between two
otherwise-identical calls with different `hours` -- a real property of the
solver, not a bug in this module, and not something a test should be
brittle against.
"""

import asyncio
from datetime import datetime, timezone

import pytest

from backend import app as app_mod
from backend.sources import sat_passes, satellites

# Same fixture as test_satellites.py's _ISS_OMM, tagged "resource" (one of
# the real CelesTrak groups behind the "imaging" toggle -- see
# satellites.ELEMENT_LAYER_GROUPS) so the decorated record carries a real
# `_layer` of "imaging", matching what an actual imaging-satellite pass
# would report.
_ISS_OMM = {
    "OBJECT_NAME": "ISS (ZARYA)",
    "OBJECT_ID": "1998-067A",
    "EPOCH": "2026-08-09T20:37:29.985312",
    "MEAN_MOTION": 15.49397757,
    "ECCENTRICITY": 0.0007373,
    "INCLINATION": 51.6326,
    "RA_OF_ASC_NODE": 34.4681,
    "ARG_OF_PERICENTER": 30.2451,
    "MEAN_ANOMALY": 329.8962,
    "EPHEMERIS_TYPE": 0,
    "CLASSIFICATION_TYPE": "U",
    "NORAD_CAT_ID": 25544,
    "ELEMENT_SET_NO": 999,
    "REV_AT_EPOCH": 58007,
    "BSTAR": 0.000083247,
    "MEAN_MOTION_DOT": 0.000042010,
    "MEAN_MOTION_DDOT": 0,
    "_group": "resource",
}


def _decorated_iss():
    return satellites._decorate_element(_ISS_OMM)


def _epoch_time():
    # The fixture's own EPOCH, as a skyfield Time -- compute_passes'
    # `start_time` param exists precisely so a test can pin the search
    # window to a fixed instant instead of "now".
    return sat_passes._ts.utc(2026, 8, 9, 20, 37, 30)


def _parse(iso: str) -> datetime:
    return datetime.fromisoformat(iso.replace("Z", "+00:00"))


# --- a known satellite over a known point, against a precomputed answer ---
#
# Tokyo (35.7N, 139.7E) has a real pass beginning ~8 minutes after this
# fixture's epoch: skyfield (run directly against this exact fixture while
# writing this test) reports rise 2026-08-09T20:45:38Z, culminate
# 2026-08-09T20:47:08Z at ~12.54 degrees elevation, set ~2026-08-09T20:48:39Z,
# duration ~180.7s. This is ISS's real orbit at a real epoch, not a synthetic
# fixture built to make the test pass.

def test_known_satellite_over_known_point_matches_precomputed_pass():
    result = sat_passes.compute_passes(
        [_decorated_iss()], lat=35.7, lon=139.7, hours=1, start_time=_epoch_time()
    )
    assert len(result["passes"]) == 1
    p = result["passes"][0]
    assert p["norad_id"] == 25544
    assert p["group"] == "imaging"
    assert p["epoch"] == "2026-08-09T20:37:29.985312"

    rise, culminate, set_ = _parse(p["rise"]), _parse(p["culminate"]), _parse(p["set"])
    assert rise == datetime(2026, 8, 9, 20, 45, 38, tzinfo=timezone.utc)
    assert culminate == datetime(2026, 8, 9, 20, 47, 8, tzinfo=timezone.utc)
    # A few seconds' slack on set only -- see this file's header on why.
    assert abs((set_ - datetime(2026, 8, 9, 20, 48, 39, tzinfo=timezone.utc)).total_seconds()) <= 3
    assert p["max_elevation_deg"] == pytest.approx(12.5365, abs=0.01)
    assert p["duration_s"] == pytest.approx(180.7, abs=3)

    assert result["satellites_total"] == 1
    assert result["satellites_reachable"] == 1
    assert result["satellites_considered"] == 1
    assert result["satellites_capped"] is False
    assert result["min_elevation_deg"] == sat_passes.PASS_MIN_ELEVATION_DEG


def test_hours_beyond_the_cap_is_silently_clamped():
    # 500 hours asked for, MAX_PASS_HOURS honoured instead -- narrowed, not
    # rejected, the same contract filter_elements_by_layer uses for an
    # unrecognised group name.
    result = sat_passes.compute_passes(
        [_decorated_iss()], lat=35.7, lon=139.7, hours=500, start_time=_epoch_time()
    )
    assert result["hours"] == sat_passes.MAX_PASS_HOURS


# --- the no-passes case ---------------------------------------------------

def test_no_passes_when_the_orbit_cannot_reach_the_latitude():
    # ISS's inclination is 51.6326 degrees; even generously padded by its
    # own visibility footprint at apogee (~20 degrees), its ground track and
    # footprint together never reach 80 degrees north -- a hard fact of the
    # orbit's geometry, not a search that merely came up empty.
    result = sat_passes.compute_passes(
        [_decorated_iss()], lat=80.0, lon=0.0, hours=24, start_time=_epoch_time()
    )
    assert result["passes"] == []
    assert result["satellites_reachable"] == 0
    assert result["satellites_considered"] == 0


def test_no_passes_when_the_element_list_is_empty():
    result = sat_passes.compute_passes([], lat=35.7, lon=139.7, hours=24, start_time=_epoch_time())
    assert result["passes"] == []
    assert result["satellites_total"] == 0


# --- the reachability pre-filter, on its own -------------------------------

def test_reachable_elements_excludes_orbits_that_cannot_reach_the_latitude():
    dec = _decorated_iss()
    assert sat_passes._reachable_elements([dec], 35.7) == [dec]
    assert sat_passes._reachable_elements([dec], 80.0) == []


def test_reachable_elements_keeps_a_record_with_no_inclination_rather_than_guessing():
    # Nothing here can safely rule an unknown-inclination record out --
    # MAX_SATELLITES_FOR_PASSES is the real backstop against an oversized
    # pool, not this filter. Both the decorated `inclination_deg` and the
    # raw OMM `INCLINATION` have to be gone for this case to be real:
    # _reachable_elements falls back to the raw field when the decorated one
    # is missing (belt and suspenders against an element set that reached
    # this function without going through satellites._decorate_element),
    # so clearing only one still leaves it with a real number to work from.
    dec = dict(_decorated_iss())
    dec["inclination_deg"] = None
    del dec["INCLINATION"]
    assert sat_passes._reachable_elements([dec], 89.0) == [dec]


# --- the work cap -----------------------------------------------------------

def test_the_satellite_cap_is_enforced_and_reported(monkeypatch):
    # A real 200-satellite search is fast (~1.5ms each, see this module's own
    # docstring) but there is no reason to pay that in a unit test -- the cap
    # is patched down to 3 and the pool is seeded with 5 identical, always-
    # reachable copies of the ISS fixture (only the NORAD id differs) so the
    # capping logic itself, not skyfield's search cost, is what is under
    # test.
    monkeypatch.setattr(sat_passes, "MAX_SATELLITES_FOR_PASSES", 3)
    pool = []
    for norad_id in (5, 4, 3, 2, 1):
        omm = dict(_ISS_OMM)
        omm["NORAD_CAT_ID"] = norad_id
        pool.append(satellites._decorate_element(omm))

    result = sat_passes.compute_passes(pool, lat=35.7, lon=139.7, hours=1, start_time=_epoch_time())

    assert result["satellites_total"] == 5
    assert result["satellites_reachable"] == 5
    assert result["satellites_considered"] == 3
    assert result["satellites_capped"] is True
    # Deterministic ordering (by NORAD id ascending), not request/dict order
    # -- the pool above was seeded in descending order specifically to prove
    # this, and the identical satellites all produce the same one pass each,
    # so which three ids show up says which three were considered.
    considered_ids = sorted({p["norad_id"] for p in result["passes"]})
    assert considered_ids == [1, 2, 3]


def test_the_passes_returned_cap_is_independent_of_the_satellite_cap(monkeypatch):
    # A handful of satellites can still produce more individual passes than
    # MAX_PASSES_RETURNED allows through in a wide-enough window -- patched
    # down here to 2 so the test does not need dozens of real orbits to prove
    # the truncation fires and is reported.
    monkeypatch.setattr(sat_passes, "MAX_PASSES_RETURNED", 2)
    dec = _decorated_iss()
    result = sat_passes.compute_passes([dec], lat=35.7, lon=139.7, hours=24, start_time=_epoch_time())
    assert len(result["passes"]) == 2
    assert result["passes_truncated"] is True


# --- footprint_radius_km, the same formula the frontend's card uses --------

def test_footprint_radius_km_is_zero_at_zero_altitude():
    assert sat_passes.footprint_radius_km(0) == 0.0


def test_footprint_radius_km_grows_with_altitude():
    low = sat_passes.footprint_radius_km(400)  # ISS-ish LEO
    high = sat_passes.footprint_radius_km(35786)  # GEO
    assert 0 < low < high


# --- the route: lat/lon validation, the groups filter, response shape -----

def _seed_imaging_elements():
    from backend.cache import registry

    registry.register("satellite_elements", key_configured=True)
    state = registry.get("satellite_elements")
    state.data = [_decorated_iss()]
    return state


def test_route_rejects_out_of_range_lat_lon():
    from fastapi import HTTPException

    _seed_imaging_elements()
    with pytest.raises(HTTPException):
        asyncio.run(app_mod.satellite_passes(lat=95.0, lon=0.0, hours=1, groups="imaging"))
    with pytest.raises(HTTPException):
        asyncio.run(app_mod.satellite_passes(lat=0.0, lon=250.0, hours=1, groups="imaging"))


def test_route_with_no_groups_serves_no_satellites_and_no_passes():
    _seed_imaging_elements()
    resp = asyncio.run(app_mod.satellite_passes(lat=35.7, lon=139.7, hours=1, groups=None))
    import json

    body = json.loads(resp.body)
    assert body["passes"] == []
    assert body["satellites_total"] == 0


def test_route_with_imaging_group_finds_the_seeded_pass(monkeypatch):
    # The route calls compute_passes with no `start_time`, i.e. real "now" --
    # pinned here to the fixture's own epoch so a one-hour window has the
    # same known pass to find that test_known_satellite_over_known_point_
    # matches_precomputed_pass already verified in detail. Without this, a
    # one-hour window starting from whatever moment the test happens to run
    # would only sometimes contain a Tokyo pass.
    monkeypatch.setattr(sat_passes._ts, "now", lambda: _epoch_time())
    _seed_imaging_elements()
    resp = asyncio.run(app_mod.satellite_passes(lat=35.7, lon=139.7, hours=1, groups="imaging"))
    import json

    body = json.loads(resp.body)
    assert body["groups"] == ["imaging"]
    assert body["satellites_total"] == 1
    assert len(body["passes"]) == 1
    assert body["passes"][0]["norad_id"] == 25544


def test_route_never_offers_a_group_the_satellite_elements_endpoint_would_refuse():
    # "active" is not a registered layer key (see test_satellites.py's own
    # coverage of this) -- asking for it here narrows to nothing, the same
    # as it does for /api/satellites/elements.
    _seed_imaging_elements()
    resp = asyncio.run(app_mod.satellite_passes(lat=35.7, lon=139.7, hours=1, groups="active"))
    import json

    body = json.loads(resp.body)
    assert body["passes"] == []
    assert body["satellites_total"] == 0
